### ISSUE TITLE
add users to group is failing

### ISSUE THREAD

**Issue by ajaychoudhary-hotstar** [harness-io/terraform-provider-harness#52] opened 2021-12-27 05:16 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- harness_add_user_to_group
- harness_user

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "harness_user" "user" {
  count = length(local.users)
  email = local.users[count.index].email
  name  = local.users[count.index].email
}

resource "harness_add_user_to_group" "add_users_to_groups" {
  count    = length(local.users)
  group_id = harness_user_group.groups[local.users[count.index].groupType].id
  user_id  = harness_user.user[count.index].id
}

resource "harness_add_user_to_group" "add_users_to_readonly_group" {
  count    = length(local.users)
  group_id = var.read_only_group_id
  user_id  = harness_user.user[count.index].id
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
While creating Harness_user, harness_group and harness_add_user_to_group, it is failing with error: Error: Exception while fetching data (/addUserToUserGroup) : Invalid request: User does not exist 
I think keeping add to group and user in seperate resource is not right solution. When we add user, it is always unverified and it seems adtogroup works if user is already verified. Add groups in harness_user resource to replicate graphQL API and UI behaviour.

### Actual Behavior
Users should be created with groups. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by micahlmartin** [comment] 2022-01-03 02:11
Duplicate of #35

**Closed by micahlmartin** 2022-01-03 02:11 UTC
